### ISSUE TITLE
[OCP4.10] Old scciclient is unexpectedly used which causes bootstrap error on iRMC IPI

### ISSUE THREAD

**Issue by hs0210** [openshift/ironic-image#234]
# What happend

OCP4.10.0-0.nightly-2021-11-12-161948 and later versions unexpectedly use old scciclient which causes bootstrap error on iRMC IPI.

# What you expected to happen?

To make sure iRMC IPI succeed, the expected version of scciclient is at least [0.9.1-0.20210827164043.21a184b.el8](https://github.com/openshift/ironic-image/blob/master/main-packages-list.ocp#L50).

# Anything else we need to know?

Until OCP 4.10.0-0.nightly-2021-11-09-181140, the version of scciclient is as follows 0.9.1-0.20210827164043.21a184b.el8.
```
sh-4.4# dnf list python3-scciclient
Last metadata expiration check: 0:00:08 ago on Wed Nov 17 06:34:41 2021.
Installed Packages
python3-scciclient.noarch 0.9.1-0.20210827164043.21a184b.el8 @rhel-8-server-ose-rpms-embargoed-x86_64
```
But from OCP 4.10.0-0.nightly-2021-11-12-161948, it uses as follows older scciclient.
```
sh-4.4# dnf list python3-scciclient
Last metadata expiration check: 0:06:58 ago on Wed Nov 17 05:58:25 2021.
Installed Packages
python3-scciclient.noarch 0.9.1-2.20210527215016.e66d50c.el8ost.1 @openstack-16-for-rhel-8-rpms-x86_64
```

From the version number, it is true that 0.9.1-2 > 0.9.1-0, but the commits they built from is 0.9.1-2 older than 0.9.1-0
- 0.9.1-2 built from [20210527215016.e66d50c](https://opendev.org/x/python-scciclient/commit/e66d50cd3fd7676b0bac82eb012b67bcf2b6e925)
- 0.9.1-0 built from [20210827164043.21a184b](https://opendev.org/x/python-scciclient/commit/21a184bff2f880a003b7841b7f967ea65fbd6091)

**Comment by elfosardo** [comment]
@hs0210 thanks for reporting this, we'll have a look ASAP

**Comment by hase1128** [comment]
we would like to use the following version(0.10.0) as base package for OpenShift.
https://pypi.org/project/python-scciclient/0.10.0/

I guess that 0.9.1-2.20210527215016.e66d50c.el8 was created by older version than 0.10.0.

**Comment by elfosardo** [comment]
> we would like to use the following version(0.10.0) as base package for OpenShift. https://pypi.org/project/python-scciclient/0.10.0/
> 
> I guess that 0.9.1-2.20210527215016.e66d50c.el8 was created by older version than 0.10.0.

yes, 0.10.0 is the intended version to use, there is a mismatch internally that we're going to fix

**Comment by elfosardo** [comment]
@hase1128 @hs0210 we're going to lock the version that includes the needed commit for the time being, that should fix the issue
then bump the version as soon as 0.10.0 is available downstream

**Comment by elfosardo** [comment]
we have 0.10.0 ready so we just switched to that
